pipeline:
    stages:
        - stage:
              variables:
                  - name: HARNESS_API_KEY
                    type: Secret
                    value: org.harness_api_key
                  - name: HARNESS_ACCOUNT_ID
                    type: Secret
                    value: org.harness_account_id
                  - name: HARNESS_ENDPOINT
                    type: String
                    value: https://app.harness.io
                  - name: HARNESS_TEST_SPOT_ACCT_ID
                    type: Secret
                    value: org.spotinst_account_id
                  - name: HARNESS_TEST_SPOT_TOKEN
                    type: Secret
                    value: org.spotinst_token
                  - name: HARNESS_TEST_AZURE_CLIENT_ID
                    type: Secret
                    value: org.azure_client_id
                  - name: HARNESS_TEST_AZURE_CLIENT_SECRET
                    type: Secret
                    value: org.azure_client_secret
                  - name: HARNESS_TEST_AZURE_TENANT_ID
                    type: Secret
                    value: org.azure_tenant_id
                  - name: HARNESS_TEST_AWS_ACCESS_KEY_ID
                    type: Secret
                    value: org.aws_access_key_id
                  - name: HARNESS_TEST_AWS_SECRET_ACCESS_KEY
                    type: Secret
                    value: org.aws_secret_access_key
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: micahs-projects
                          connectorRef: account.micahsprojects
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheGCS
                                spec:
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                                    key: harness-go-sdk-{{ checksum "go.mod" }}
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    archiveFormat: Gzip
                                name: Restore from cache
                                identifier: Restore_from_cache
                          - step:
                                type: Run
                                spec:
                                    privileged: false
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-10
                                    connectorRef: org.gcp
                                    command: go mod vendor
                                name: Download modules
                                identifier: Download_modules
                          - step:
                                type: SaveCacheGCS
                                spec:
                                    sourcePaths:
                                        - ./vendor
                                    key: harness-go-sdk-{{ checksum "go.mod" }}
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    archiveFormat: Gzip
                                name: Save cache
                                identifier: Save_cache
                          - parallel:
                                - step:
                                      type: Run
                                      spec:
                                          connectorRef: org.gcp
                                          image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-10
                                          command: golangci-lint run -v
                                          privileged: false
                                          resources:
                                              limits:
                                                  memory: 2Gi
                                                  cpu: "1"
                                      name: Lint
                                      identifier: lint
                                - step:
                                      type: Run
                                      spec:
                                          resources:
                                              limits:
                                                  memory: 2Gi
                                                  cpu: "2"
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - junit.xml
                                          privileged: false
                                          image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-10
                                          connectorRef: org.gcp
                                          command: |
                                              gotestsum --junitfile junit.xml --format testname
                                      name: Test
                                      identifier: Test
                  cloneCodebase: true
              name: Build
              identifier: Build
    properties:
        ci:
            codebase:
                repoName: harness-go-sdk
                connectorRef: org.githubharnessio
                build: <+input>
    projectIdentifier: harness_gos_dk
    orgIdentifier: Micahs_Projects
    name: ci
    identifier: ci
